spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ORCLCDB.localdomain)))
    username: SANDBOX_DEV
    password: dev

  liquibase:
    change-log: classpath:liquibase-changeLog.xml

  jpa:
    properties:
      hibernate:
        format_sql: true

service-config:
  value: default