server:
  port: 8090

service-config:
  value: default

spring:
  security:
    user:
      name: test
      password: test

collections:
  chronicle:
    path: /Desktop/country-details.dat

logging:
  level:
    root: INFO